### ISSUE TITLE
Basic usage

### ISSUE THREAD

**Issue by maiorfi** [andars/pebble-controller#1]
Hi.

Please forgive me if I'm asking for something obvious, but I just tried your app on my PebbleTime (+ android phone) and there is something I can't understand.

Since I'd like to use my own tcp server, I just ran on myPC a simple tool that dumps raw tcp-in data incoming on port 5000 (i.e. telnetting to such endpoint from a second PC I see data flowing). After doing that, I connected to same wifi network from my smartphone and launched PebbleTime app, selecting my PC network address.

THen, I was expecting that clicking on watch buttons I would see data flowing on my dump tool, but this is not the case: nothing happens.

Any idea?

Thanks!

**Comment by andars** [comment]
Hmmm... nothing immediately comes to mind. Could you try again and see what the logs from the watch look like? If you don't know how, read [this](http://developer.getpebble.com/guides/pebble-apps/debugging/debugging-guide/#viewing-log-data).
