### ISSUE TITLE
Problem on windows

### ISSUE THREAD

**Issue by thucngocle** [andars/pebble-controller#2]
I'm a developer. I'm coding a program listen on port: 5000.

My program run on windows 7 and using .Net framework 2.0. But it not working. PC and mobile phone same network (ping ok). Please help me !

**Comment by thucngocle** [comment]
Here is my code:

Imports System.Net
Imports System.Net.Sockets
Imports System.IO
Public Class Form1
    Private Sub Form1_Load(ByVal sender As System.Object, ByVal e As System.EventArgs) Handles MyBase.Load
        Dim t As New Threading.Thread(AddressOf ThucthiTCP)
        t.Start()
    End Sub
    Sub ThucthiTCP()
        Try
            Dim l As New TcpListener(5000)
            'Lắng nghe dữ liệu
            l.Start()
            Control.CheckForIllegalCrossThreadCalls = False
            txtKetQua.Text = "Đang lắng nghe trên port: 5000" & vbNewLine
            Dim s As Socket
            s = l.AcceptSocket
            txtKetQua.Text &= "Kết nối được nhận từ máy: " & s.RemoteEndPoint.ToString & vbNewLine
            Dim ntStream As New NetworkStream(s)
            Dim reader As New StreamReader(ntStream)  
            While True
                Dim strData As String
                'Nhận dữ liệu
                strData = reader.ReadLine
                If strData <> "" Then
                    txtKetQua.Text &= strData & vbNewLine  
                End If  
            End While
            ntStream.Close()
            s.Close()
            l.Stop()
        Catch ex As Exception
            MsgBox(ex.Message)
        End Try
    End Sub
End Class

**Comment by andars** [comment]
Unfortunately I am not familiar with either .NET or Visual Basic, so I won't be able to help you. One thing that comes to mind is that the pebble application sends data as POST requests over HTTP, which will not necessarily reuse the same TCP connection for each request.

**Comment by thucngocle** [comment]
But are these "pebble controller" send key press to IP server running on port 5000 ???

```
 Vào ngày 12:53 Thứ Ba, 17 tháng 11 2015, Andrew Foote <notifications@github.com> đã viết:
```

 Unfortunately I am not familiar with either .NET or Visual Basic, so I won't be able to help you. One thing that comes to mind is that the pebble application sends data as POST requests over HTTP, which will not necessarily reuse the same TCP connection for each request.—

**Comment by andars** [comment]
If I understand you correctly, the answer is yes. Running `nc -k -l 0.0.0.0 5000` (netcat as server on port 5000) yields:

```
POST /data HTTP/1.1
Host: 10.0.1.2:5000
Content-Type: application/x-www-form-urlencoded
User-Agent: PebbleApp/20151005205738 CFNetwork/711.5.6 Darwin/14.0.0
Accept: */*
Accept-Language: en-us
Content-Length: 8
Accept-Encoding: gzip, deflate
Connection: keep-alive

button=2
```

**Comment by thucngocle** [comment]
Thank you for reply !
I run nc -l -p 5000 to lisen on port 5000.
I press key on pebble but Nothing happenned. pebble-controller app not show connection information. pebble app running android 4.0 and still working normally. please help me !

```
Vào ngày 14:26 Thứ Ba, 17 tháng 11 2015, Andrew Foote <notifications@github.com> đã viết:
```

 If I understand you correctly, the answer is yes. Running nc -k -l 0.0.0.0 5000 (netcat as server on port 5000) yields:POST /data HTTP/1.1
Host: 10.0.1.2:5000
Content-Type: application/x-www-form-urlencoded
User-Agent: PebbleApp/20151005205738 CFNetwork/711.5.6 Darwin/14.0.0
Accept: _/_
Accept-Language: en-us
Content-Length: 8
Accept-Encoding: gzip, deflate
Connection: keep-alive

button=2

**Comment by thucngocle** [comment]
How to check my pebble-controller connected successfull to ip server on port 5000.My pebble-controller always show this screen: (view attach file, my ip server: 192.169.6.202, on my mobile execute ping and tracert to ip server ok)

```
Vào ngày 14:26 Thứ Ba, 17 tháng 11 2015, Andrew Foote <notifications@github.com> đã viết:
```

 If I understand you correctly, the answer is yes. Running nc -k -l 0.0.0.0 5000 (netcat as server on port 5000) yields:POST /data HTTP/1.1
Host: 10.0.1.2:5000
Content-Type: application/x-www-form-urlencoded
User-Agent: PebbleApp/20151005205738 CFNetwork/711.5.6 Darwin/14.0.0
Accept: _/_
Accept-Language: en-us
Content-Length: 8
Accept-Encoding: gzip, deflate
Connection: keep-alive

button=2

**Comment by andars** [comment]
Like I said, I am not familiar with either VB or .NET, and I have never used windows for any development. If your tcp server is working correctly and you have entered the correct IP on the watch, you should receive data similar to the above. I would recommend trying the existing rust or ruby servers.
