### ISSUE TITLE
exit the app on Pebble without reporting a button press?

### ISSUE THREAD

**Issue by yesyesuk** [andars/pebble-controller#3]
Hi,
I like your Pebble-controller, thanks for providing it.
I'm developing my own home automation and would like to support pebble-controller to be able to control a few often used functions from my watch (something like "all lights off").

I've been playing around with it and I'm able to receive the HTTP POST in a test C# app.

The "problem" I have is that it seems the only way to exit the app running on Pebble is to long-press the back button on the watch. However, that also reports that this button (button=0 if I remember correctly) has been pressed. This makes it almost impossible to use that button because every time I exit the app the function assigned to that button would be executed.

Can you think of any way around that? 
Maybe the HTTP POST could be sent when the button is being released, rather than when it's pressed? I assume when exiting the app the release of the "back" button would no longer be reported because the app is closed.

**Comment by andars** [comment]
Pebble is (more or less) dead, and I don't plan on ever updating this. Closing.
